import { theme } from "../theme";

/**
 * The Monaco theme built from the design tokens: the editor is the page's
 * ground, keywords are the one lime accent, strings warm, numbers cool,
 * comments dim. The only place besides theme.ts that spells a colour: Monaco
 * wants hex strings, not CSS variables.
 */
export const MONACO_THEME = "gorbital-dark";

/** A hex colour with an alpha byte appended, for Monaco's UI colours. */
const alpha = (hex: string, a: number) => `${hex}${Math.round(a * 255).toString(16).padStart(2, "0")}`;

export const monacoTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: theme.text.slice(1) },
    { token: "keyword", foreground: theme.primary.slice(1), fontStyle: "bold" },
    { token: "operator", foreground: theme.muted.slice(1) },
    { token: "delimiter", foreground: theme.dim.slice(1) },
    { token: "identifier", foreground: theme.text.slice(1) },
    { token: "identifier.quote", foreground: theme.dim.slice(1) },
    { token: "predefined", foreground: theme.violet.slice(1) },
    { token: "string", foreground: theme.warn.slice(1) },
    { token: "number", foreground: theme.info.slice(1) },
    { token: "comment", foreground: theme.dim.slice(1), fontStyle: "italic" },
    { token: "comment.quote", foreground: theme.dim.slice(1), fontStyle: "italic" },
    { token: "white", foreground: theme.text.slice(1) },
  ],
  colors: {
    "editor.background": theme.bg,
    "editor.foreground": theme.text,
    "editorLineNumber.foreground": theme.faint,
    "editorLineNumber.activeForeground": theme.dim,
    "editorCursor.foreground": theme.primary,
    "editor.selectionBackground": alpha(theme.primary, 0.22),
    "editor.inactiveSelectionBackground": alpha(theme.primary, 0.12),
    "editor.selectionHighlightBackground": alpha(theme.primary, 0.1),
    "editor.lineHighlightBackground": alpha(theme.surface, 0.9),
    "editor.lineHighlightBorder": theme.hairline,
    "editor.wordHighlightBackground": alpha(theme.info, 0.12),
    "editor.findMatchBackground": alpha(theme.warn, 0.35),
    "editor.findMatchHighlightBackground": alpha(theme.warn, 0.18),
    "editorBracketMatch.background": alpha(theme.primary, 0.15),
    "editorBracketMatch.border": theme.primaryMid,
    "editorBracketHighlight.foreground1": theme.primarySoft,
    "editorBracketHighlight.foreground2": theme.info,
    "editorBracketHighlight.foreground3": theme.violet,
    "editorIndentGuide.background1": theme.hairline,
    "editorIndentGuide.activeBackground1": theme.border2,
    "editorWhitespace.foreground": theme.hairline,
    "editorGutter.background": theme.bg,
    "editorError.foreground": theme.danger,
    "editorWarning.foreground": theme.warn,
    "editorInfo.foreground": theme.info,
    "editorMarkerNavigationError.background": theme.danger,
    "editorOverviewRuler.border": theme.bg,
    "editorOverviewRuler.errorForeground": theme.danger,
    "editorWidget.background": theme.elevated,
    "editorWidget.border": theme.border,
    "editorWidget.foreground": theme.text,
    "editorSuggestWidget.background": theme.elevated,
    "editorSuggestWidget.border": theme.border,
    "editorSuggestWidget.foreground": theme.text,
    "editorSuggestWidget.selectedBackground": theme.raised,
    "editorSuggestWidget.selectedForeground": theme.text,
    "editorSuggestWidget.highlightForeground": theme.primary,
    "editorSuggestWidget.focusHighlightForeground": theme.primarySoft,
    "editorHoverWidget.background": theme.elevated,
    "editorHoverWidget.border": theme.border,
    "input.background": theme.codeBg,
    "input.border": theme.border,
    "input.foreground": theme.text,
    "input.placeholderForeground": theme.faint,
    "inputOption.activeBorder": theme.primaryMid,
    "inputOption.activeBackground": alpha(theme.primary, 0.15),
    "focusBorder": alpha(theme.primary, 0.5),
    "list.hoverBackground": theme.raised,
    "list.focusBackground": theme.raised,
    "list.activeSelectionBackground": theme.raised,
    "scrollbarSlider.background": alpha(theme.border2, 0.6),
    "scrollbarSlider.hoverBackground": alpha(theme.border2, 0.9),
    "scrollbarSlider.activeBackground": theme.border2,
    "scrollbar.shadow": alpha(theme.bg, 0),
    "widget.shadow": alpha(theme.bg, 0.6),
    "minimap.background": theme.bg,
    "textLink.foreground": theme.primary,
    "textLink.activeForeground": theme.primarySoft,
    "editorLink.activeForeground": theme.primary,
    "editorLineNumber.dimmedForeground": theme.faint,
    "editorCodeLens.foreground": theme.dim,
    "editorGhostText.foreground": theme.faint,
    "editorStickyScroll.background": theme.bg,
    "editorStickyScroll.shadow": alpha(theme.bg, 0),
    "peekView.border": theme.border,
    "badge.background": theme.primaryDeep,
    "badge.foreground": theme.primarySoft,
    "quickInput.background": theme.elevated,
    "quickInput.foreground": theme.text,
    "pickerGroup.foreground": theme.primary,
    "keybindingLabel.background": theme.codeBg,
    "keybindingLabel.border": theme.border,
    "keybindingLabel.bottomBorder": theme.border2,
    "keybindingLabel.foreground": theme.dim,
  },
};

/** Editor options that don't change per instance. */
export const monacoDefaults = {
  fontFamily: 'var(--font-geist-mono), "Geist Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
  fontSize: 12.5,
  lineHeight: 20,
  letterSpacing: 0,
  fontLigatures: false,
  minimap: { enabled: false },
  lineNumbers: "on" as const,
  lineNumbersMinChars: 3,
  glyphMargin: false,
  folding: false,
  matchBrackets: "always" as const,
  bracketPairColorization: { enabled: true },
  renderLineHighlight: "line" as const,
  scrollBeyondLastLine: false,
  smoothScrolling: true,
  cursorBlinking: "smooth" as const,
  cursorSmoothCaretAnimation: "on" as const,
  padding: { top: 10, bottom: 10 },
  scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8, useShadows: false },
  overviewRulerBorder: false,
  overviewRulerLanes: 2,
  hideCursorInOverviewRuler: true,
  wordWrap: "off" as const,
  tabSize: 2,
  insertSpaces: true,
  automaticLayout: true,
  fixedOverflowWidgets: true,
  quickSuggestions: { other: true, comments: false, strings: false },
  suggestOnTriggerCharacters: true,
  acceptSuggestionOnEnter: "on" as const,
  wordBasedSuggestions: "off" as const,
  suggest: { showWords: false, preview: false },
  contextmenu: false,
  stickyScroll: { enabled: false },
  guides: { indentation: true, bracketPairs: false },
  renderWhitespace: "none" as const,
  occurrencesHighlight: "singleFile" as const,
  selectionHighlight: true,
  roundedSelection: true,
  unicodeHighlight: { ambiguousCharacters: false },
};
