"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, Settings2, X } from "lucide-react";
import { Checkbox, Field, Input, Label, Select } from "@gorbital/dash/components/input";
import { Tooltip } from "@gorbital/dash/components/tooltip";
import type { Identity, TypeOption } from "@/lib/api/db";
import { integerTypes, type ColumnForm } from "@/lib/table-editor/plan";
import { FKPicker, emptyFK } from "./fk-picker";
import { TypePicker, splitSized } from "./type-picker";

type Props = {
  form: ColumnForm;
  onChange: (f: ColumnForm) => void;
  types: TypeOption[] | undefined;
  mode: "create" | "edit";
  /** One row per column, the essentials inline and the rest behind a toggle (the new-table sheet). */
  compact?: boolean;
  onRemove?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  error?: string;
};

const chip = "h-5 rounded-md border border-border px-1.5 font-mono text-[10.5px] text-dim hover:border-border-2 hover:text-text";

export function ColumnFields({ form, onChange, types, mode, compact, onRemove, onMoveUp, onMoveDown, error }: Props) {
  const [expanded, setExpanded] = useState(false);
  const set = (patch: Partial<ColumnForm>) => onChange({ ...form, ...patch });
  const base = splitSized(form.type).base;
  const option = types?.find((t) => t.name === base);
  const isInt = integerTypes.includes(form.type);
  const suggestions = [...(option?.suggestions ?? []), ...(form.array ? ["'{}'"] : [])].filter((s, i, a) => a.indexOf(s) === i);

  const nameField = <Input mono value={form.name} onChange={(e) => set({ name: e.target.value })} placeholder="column_name" aria-label="Column name" aria-invalid={error ? true : undefined} autoComplete="off" spellCheck={false} />;
  const typeField = <TypePicker value={form.type} onChange={(type) => set({ type, identity: integerTypes.includes(type) ? form.identity : "none" })} types={types} array={form.array} onArray={(array) => set({ array })} />;
  const defaultField = (
    <div className="grid gap-1.5">
      <Input mono value={form.default} onChange={(e) => set({ default: e.target.value })} placeholder={form.identity !== "none" ? "generated" : "no default"} aria-label="Default" disabled={form.identity !== "none"} spellCheck={false} />
      {!compact && (
        <div className="flex flex-wrap items-center gap-1.5">
          <label className="flex items-center gap-1.5 text-[11px] text-muted">
            <Checkbox checked={form.defaultIsExpr} onCheckedChange={(v) => set({ defaultIsExpr: v === true })} aria-label="Default is an expression" />
            expression
          </label>
          {suggestions.map((s) => (
            <button key={s} type="button" className={chip} onClick={() => set({ default: s, defaultIsExpr: true })}>
              {s}
            </button>
          ))}
        </div>
      )}
    </div>
  );
  const nullable = (
    <label className="flex items-center gap-1.5 text-[11.5px] text-text">
      <Checkbox checked={form.nullable && !form.primaryKey} onCheckedChange={(v) => set({ nullable: v === true })} disabled={form.primaryKey} aria-label="Nullable" />
      nullable
    </label>
  );
  const primary = (
    <label className="flex items-center gap-1.5 text-[11.5px] text-text">
      <Checkbox checked={form.primaryKey} onCheckedChange={(v) => set({ primaryKey: v === true, nullable: v === true ? false : form.nullable })} disabled={mode === "edit"} aria-label="Primary key" />
      primary key
    </label>
  );
  const unique = (
    <label className="flex items-center gap-1.5 text-[11.5px] text-text">
      <Checkbox checked={form.unique} onCheckedChange={(v) => set({ unique: v === true })} disabled={form.primaryKey} aria-label="Unique" />
      unique
    </label>
  );
  const identity = (
    <Field label="Identity" hint={isInt ? "the database numbers the rows" : "needs int2, int4 or int8"}>
      <Select value={form.identity} onChange={(e) => set({ identity: e.target.value as Identity, default: e.target.value === "none" ? form.default : "" })} disabled={!isInt} aria-label="Identity">
        <option value="none">none</option>
        <option value="by_default">generated by default</option>
        <option value="always">generated always</option>
      </Select>
    </Field>
  );
  const check = (
    <Field label={mode === "edit" ? "Add check constraint" : "Check"} hint="an expression over this row, e.g. amount >= 0">
      <Input mono value={form.check} onChange={(e) => set({ check: e.target.value })} placeholder="expression" aria-label="Check" spellCheck={false} />
    </Field>
  );
  const comment = (
    <Field label="Comment">
      <Input value={form.comment} onChange={(e) => set({ comment: e.target.value })} placeholder="what the column holds" aria-label="Comment" />
    </Field>
  );
  const references = mode === "create" && (
    <div className="grid gap-2">
      <label className="flex items-center gap-1.5 text-[11.5px] text-text">
        <Checkbox checked={Boolean(form.references)} onCheckedChange={(v) => set({ references: v === true ? emptyFK() : undefined })} aria-label="References another table" />
        references another table
      </label>
      {form.references && <FKPicker value={form.references} onChange={(references) => set({ references })} localColumns={[form.name || "column"]} />}
    </div>
  );

  if (!compact) {
    return (
      <div className="grid gap-3">
        <Field label="Name" error={error}>
          {nameField}
        </Field>
        <Field label="Type">{typeField}</Field>
        <Field label="Default" hint={form.identity !== "none" ? undefined : "a literal, or an expression such as now()"}>
          {defaultField}
        </Field>
        <div className="flex flex-wrap items-center gap-4">
          {nullable}
          {primary}
          {unique}
        </div>
        {identity}
        {check}
        {comment}
        {references}
      </div>
    );
  }

  return (
    <div className={`rounded-lg border ${error ? "border-danger/40" : "border-hairline"} bg-bg/40 p-2`}>
      <div className="grid grid-cols-[minmax(120px,1.1fr)_minmax(200px,1.6fr)_minmax(90px,1fr)_auto] items-center gap-2">
        {nameField}
        {typeField}
        {defaultField}
        <div className="flex items-center gap-2.5">
          <Tooltip content="nullable">
            <span>
              <Checkbox checked={form.nullable && !form.primaryKey} onCheckedChange={(v) => set({ nullable: v === true })} disabled={form.primaryKey} aria-label="Nullable" />
            </span>
          </Tooltip>
          <Tooltip content="primary key">
            <button type="button" onClick={() => set({ primaryKey: !form.primaryKey, nullable: !form.primaryKey ? false : form.nullable })} className={`h-5 rounded-md border px-1.5 font-mono text-[10px] ${form.primaryKey ? "border-warn/40 bg-warn/10 text-warn" : "border-border text-dim hover:text-text"}`} aria-pressed={form.primaryKey}>
              PK
            </button>
          </Tooltip>
          <Tooltip content="more settings">
            <button type="button" onClick={() => setExpanded((v) => !v)} className={`grid h-6 w-6 place-items-center rounded text-dim hover:bg-elevated hover:text-text ${expanded ? "text-primary" : ""}`} aria-expanded={expanded} aria-label="More settings">
              <Settings2 size={13} />
            </button>
          </Tooltip>
          <span className="flex">
            <button type="button" onClick={onMoveUp} disabled={!onMoveUp} className="grid h-6 w-5 place-items-center rounded text-dim hover:text-text disabled:opacity-30" aria-label="Move up">
              <ChevronUp size={12} />
            </button>
            <button type="button" onClick={onMoveDown} disabled={!onMoveDown} className="grid h-6 w-5 place-items-center rounded text-dim hover:text-text disabled:opacity-30" aria-label="Move down">
              <ChevronDown size={12} />
            </button>
          </span>
          <button type="button" onClick={onRemove} disabled={!onRemove} className="grid h-6 w-6 place-items-center rounded text-dim hover:bg-danger/10 hover:text-danger disabled:opacity-30" aria-label="Remove column">
            <X size={13} />
          </button>
        </div>
      </div>
      {error && <div className="mt-1 text-[11px] text-danger">{error}</div>}
      {expanded && (
        <div className="mt-2 grid gap-3 border-t border-hairline pt-3">
          <div className="grid gap-1">
            <Label>Default</Label>
            <div className="flex flex-wrap items-center gap-1.5">
              <label className="flex items-center gap-1.5 text-[11px] text-muted">
                <Checkbox checked={form.defaultIsExpr} onCheckedChange={(v) => set({ defaultIsExpr: v === true })} aria-label="Default is an expression" />
                expression
              </label>
              {suggestions.map((s) => (
                <button key={s} type="button" className={chip} onClick={() => set({ default: s, defaultIsExpr: true })}>
                  {s}
                </button>
              ))}
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-4">{unique}</div>
          <div className="grid grid-cols-2 gap-3">
            {identity}
            {comment}
          </div>
          {check}
          {references}
        </div>
      )}
    </div>
  );
}
